### ISSUE TITLE
Update node and NPM versions

### ISSUE THREAD

**Issue by Sidsector9** [10up/insecure-content-warning#114]
### Is your enhancement related to a problem? Please describe.

`@10up/eslint-config` couldn't be updated as it couldn't satisfy the node and NPM requirements.

Adding to it, after upgrading node to 16, `stylelint` fails during installation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kmgalanakis** [comment]
In [this commit](https://github.com/10up/insecure-content-warning/commit/1694ff053675b637aebe591fa02248f0fb5fb21a) we updated the build process for the plugin . The `@10up/eslint-config` and the `stylelint` packages are no longer used.

The only thing that we could do in the context of this ticket is to update the minimum node version for this plugin to `16.0.0`.

What do you think @jeffpaul?

**Comment by jeffpaul** [comment]
@kmgalanakis seems like we can bump node and remove those two packages?  (cc: @Sidsector9 )

**Comment by Sidsector9** [comment]
@kmgalanakis agreed, I think we updating the following would do:

https://github.com/10up/insecure-content-warning/blob/4052423fd73bff878c707e2cae2b8f92a7f30a3f/package.json#L48
