### ISSUE TITLE
Move warning messages to pre-publish panel

### ISSUE THREAD

**Issue by adamsilverstein** [10up/insecure-content-warning#14]
The warning messages really belong in the pre-publish panel where the user is reviewing information about the post before publishing it:

![](https://cl.ly/3L3S1G2o041m/[c2752168fb130d7eb9cee46a86c522da]_Image%202018-05-24%20at%204.19.41%20PM.png)

A new API was recently introduced in Gutenberg that adds a slot in the pre-publish panel we can leverage:

https://github.com/WordPress/gutenberg/pull/6798

Here is a code sample from the PR that uses the slot: https://gist.github.com/gziolo/fd8141f2cde7fcb1b513c09eea45d27f (you can paste this into your browser!)

**Comment by jeffpaul** [comment]
Closing this as there's been no community feedback on the topic and otherwise view the existing location as perfectly reasonable at this time.
