### ISSUE TITLE
Consider moving warning messages above post in classic editor

### ISSUE THREAD

**Issue by adamsilverstein** [10up/insecure-content-warning#20]
![](https://cl.ly/410X2M1k1i1W/[de98487437c049eea80036eaaa989f26]_Image%202018-07-11%20at%2010.13.36%20AM.png)

we probably want to think about how we ensure it gets seen, if it happens before a page reload.

**Comment by jeffpaul** [comment]
Closing this as there's been no community feedback on the topic and otherwise view the existing location as perfectly reasonable at this time.
