### ISSUE TITLE
Test against WordPress 5.8

### ISSUE THREAD

**Issue by jeffpaul** [10up/insecure-content-warning#48]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.8 is released, we'll want to test Insecure Content Warning to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test Insecure Content Warning on WordPress 5.8
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
Related: n/a.

**Comment by ajmaurya99** [comment]
Hey @jeffpaul I have tested the plugin with WP 5.8.1 and everything works as expected.
I tried adding insecure image and video and these were the results.

<img width="280" alt="Screenshot 2021-10-08 at 7 31 23 PM" src="https://user-images.githubusercontent.com/9847340/136571948-14b1b1ef-0243-4e8d-b878-3367d4b7b385.png">

**Comment by jeffpaul** [comment]
@ajmaurya99 thanks!  Feel free to open a PR to bump these to 5.8:
https://github.com/10up/insecure-content-warning/blob/17409e3f9859a8699e017c4301caac72056a6982/readme.txt#L5
https://github.com/10up/insecure-content-warning/blob/develop/README.md (see current 5.7 badge)
