### ISSUE TITLE
Uploading/selecting an insecure featured image doesn't throw any warnings

### ISSUE THREAD

**Issue by Sidsector9** [10up/insecure-content-warning#52]
**Is your enhancement related to a problem? Please describe.**

We only look at `post_content` so the featured image is never considered. This would be a new feature to add.

**Additional links**
Link to the thread can be found [here](https://tenup.teamwork.com/#/tasks/18929523?c=9024774).

**Comment by jeffpaul** [comment]
[WP 5.7](https://wordpress.org/news/2021/03/esperanza/) added the ability for content to be updated from HTTP to HTTPS more gracefully, so yes let's go ahead and close this for now but if there are community reports of issues with media library content then we can re-investigate more detailed messaging for users on how to update their site with SSL & HTTPS.
