### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by jeffpaul** [10up/insecure-content-warning#62]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.9 is released, we'll want to test Insecure Content Warning to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test Insecure Content Warning on WordPress 5.9
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
Related: #48.

**Comment by mohitwp** [comment]
QA Update : Tested and compare with WP version 5.8,3 and 5.9.
Found one compatibility issue with WP version 5.9
Issue link : https://github.com/10up/insecure-content-warning/issues/63

cc @jeffpaul @ankitguptaindia

**Comment by jeffpaul** [comment]
Closed by #64
