### ISSUE TITLE
5.9 Compatibility issue > Fix is not working and user is not able to publish page or post.

### ISSUE THREAD

**Issue by mohitwp** [10up/insecure-content-warning#63]
### Describe the bug

I tested 'insecure-content-warning' plugin version -1.0.0 with `WP version 5 8.3` and` WP version 5.9` and I found that on WP 5.9 version 'Fix' functionality of the plugin is not working and when user clicks on "FIX" button then nothing happens and user is not able to publish a page or post.  
In WP 5.8.3 insecure content URL is getting fix when user clicks on 'FIX' button. User can publish post or page and 'HTTPS' is appearing in a link of insecure content instead of 'HTTP' after fixing content.

### Steps to Reproduce

1. Install Plugin.
2. Add page or post.
3. Add media through insecure URL. Ex: http://www.goodmorningimagesdownload.com/wp-content/uploads/2019/12/Love-Images-4.jpg
4. Try to publish page or post.
5. You will see insecure content error.
6. Try to fix the content.
7. Notice issue.

### Screenshots, screen recording, code snippet

Uploading Recording #34.mp4…

### Environment information

Windows 11
Chrome version - 97.0.4692.71

### WordPress information

WP version 5.9 RC1
Insecure content warning plugin version - 1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankitguptaindia** [comment]
Hello @jeffpaul Please assign this issue to the respective team member to fix. This is a compatibility issue with WP 5.9.

**Comment by peterwilsoncc** [comment]
I've reached out to a Gutenberg team member to see if this was a bug introduced in 5.9 or an intentional deprecation. I'll be opening an issue on WordPress/Gutenberg.

The replacement approach in the linked pull request looks like it's within warranty vs the old approach skirting the edges so I think it's a nice improvement none-the-less.
