### ISSUE TITLE
Doesn't see insecure elements inside Classic Block

### ISSUE THREAD

**Issue by cadic** [10up/insecure-content-warning#72]
### Describe the bug

When saving a page which have a Classic Block on it containing insecure elements, the plugin doesn't find them and saves the post without a warning.

### Steps to Reproduce

1. Create new post with Classic Editor, add insecure elements
2. Save the post with insecure elements
3. Insecure Warning is shown
4. Click "Publish with insecure assets" and publish the post
5. Open the post in Block Editor
6. The content is in single "Classic" Block
7. Save the post
8. **The post is saved without Insecure warning**

Expected to see Insecure Warning when saving the post with insecure elements inside Classic Block

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/288381/169985088-d5331e9d-756b-485c-9917-a8be3d901b75.mp4

### WordPress information

<details>`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: local
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/cadic/Sites/wordpress/app/public
wordpress_size: loading...
uploads_path: /Users/cadic/Sites/wordpress/app/public/wp-content/uploads
uploads_size: loading...
themes_path: /Users/cadic/Sites/wordpress/app/public/wp-content/themes
themes_size: loading...
plugins_path: /Users/cadic/Sites/wordpress/app/public/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: Storefront (storefront)
version: 4.1.0
author: Automattic
author_website: https://woocommerce.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, post-thumbnails, custom-logo, menus, html5, custom-background, custom-header, site-logo, title-tag, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-style, responsive-embeds, starter-content, widgets
theme_path: /Users/cadic/Sites/wordpress/app/public/wp-content/themes/storefront
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Insecure Content Warning: version: 1.0.1, author: 10up, Auto-updates disabled

### wp-plugins-inactive (16) ###

Block for Apple Maps: version: 1.0.2, author: 10up, Auto-updates disabled
Cypress WP Utils: author: (undefined), version: (undefined), Auto-updates disabled
Debug Bar: version: 1.1.3, author: wordpressdotorg, Auto-updates disabled
Debug Bar for Sophi: version: 0.2.0, author: 10up, Auto-updates disabled
Simple Local Avatars: version: 2.4.0, author: Jake Goldman, 10up, Auto-updates disabled
Simple Page Ordering: version: 2.4.0, author: Jake Goldman, 10up, Auto-updates disabled
Simple Podcasting: version: 1.2.3, author: 10up, Auto-updates disabled
Sophi: version: 1.1.3-dev, author: 10up, Auto-updates disabled
WooCommerce: version: 6.5.1, author: Automattic, Auto-updates disabled
WooCommerce Bookings: version: 1.15.55, author: WooCommerce, Auto-updates disabled
WooCommerce Box Office: version: 1.1.36, author: WooCommerce, Auto-updates disabled
WooCommerce Deposits: version: 1.5.10, author: WooCommerce, Auto-updates disabled
WooCommerce Eway Payment Gateway: version: 3.4.2, author: WooCommerce, Auto-updates disabled
WooCommerce Framework Plugin TODO: plugin name: version: 1.0.0 TODO: plugin version, author: SkyVerge, Auto-updates disabled
WooCommerce Square: version: 3.0.1, author: WooCommerce (latest version: 3.0.2), Auto-updates disabled
WooCommerce Xero Integration: version: 1.7.42, author: WooCommerce, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 21.4.0 x86_64
httpd_software: nginx/1.16.0
php_version: 8.0.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_filesize: 300M
php_post_max_size: 1000M
curl_version: 7.79.1 (SecureTransport) LibreSSL/3.3.5
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 8.0.0
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/cadic/Sites/wordpress/app/public/wp-content
WP_PLUGIN_DIR: /Users/cadic/Sites/wordpress/app/public/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: local
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noraconley** [comment]
This issue is also present when placing an HTML block with insecure content without a parent.

This **is not** detected:
`<img src="http://google.com/dummy1.jpg" />`

This **is** detected:
`<figure><img src="http://google.com/dummy1.jpg" /></figure>`
